version: '3'
#为什么是3阿

services:
  #指定服务名称
  mysql:
    #指定服务使用的镜像
    image: mysql
    #指定容器名称
    container_name: mysql
    #指定服务运行的端口
    #暴露端口信息-"宿主机端口:容器暴露端口"
    #mysql默认端口是3306，然后我在之前mysql产生的容器中暴露的端口是8888
    #IDEA上项目也能连到数据库，这里的端口我就有点搞不懂了
    ports:
      - 8888:3306

    #指定容器环境变量
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: springboot_study
      MYSQL_ROOT_PASSWORD: 123456
    #容器总是重新启动
    restart: always

  #Springboot项目服务
  springjpa:
    #指定镜像
    image: springjpa
    #指定容器名称
    container_name: springjpa
    restart: always
    #指定服务运行端口
    ports:
      - 8080:8080
    #服务依赖
    depends_on:
      - mysql

  springmybatis:
    #指定镜像
    image: springmybatis
    #指定容器名称
    container_name: springmybatis
    restart: always
    #指定服务运行端口
    ports:
      - 8081:8080
    #服务依赖
    depends_on:
      - mysql

  springmybatis-plus:
    #指定镜像
    image: springmybatis-plus
    #指定容器名称
    container_name: springmybatis-plus
    restart: always
    #指定服务运行端口
    ports:
      - 8082:8080
    #服务依赖
    depends_on:
      - mysql