###
POST http://localhost:8080/role
Accept: application/json
Content-Type: application/json

{
  "roleName": "admin55"
}

###
PUT http://localhost:8080/role
Accept: application/json
Content-Type: application/json

{
  "id": 19,
  "roleName": "admin1"
}

###
GET http://localhost:8080/role/19
Accept: application/json

###
GET http://localhost:8080/role
Accept: application/json

###
POST http://localhost:8080/role/add-user-n-roles
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "userName": "7kk",
  "roleList": [
	{
	  "roleName": "scientist"
	},
	{
	  "roleName": "gymnast"
	}
  ]
}