spring:
  main:
    ##todo 应该可以解决循环依赖
    allow-circular-references: false
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    #todo 你服务器部署一个，用服务器的
    url:  jdbc:mysql://159.75.120.222:3306/springboot_study?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl