spring:
  jpa:
    #???????????????????????InnoDB??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #?????????sql??
    show-sql: true
    #?????????????????????????
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  
  # ???????
  datasource:
    # ???????
    type: com.zaxxer.hikari.HikariDataSource
    # ????????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_study?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456